name: Acceptance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 1-5'
      timezone: "Europe/Paris"

permissions:
  contents: read

jobs:
  atest:
    name: Acceptance tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip

      - name: Installation
        run: pip install -e .

      - name: Run acceptance tests
        env:
          LYNQA_API_KEY: ${{ secrets.LYNQA_API_KEY }}
        run: robot --outputdir results src/robotframework_lynqa/atest

      - name: Upload Robot Framework reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: acceptance-results
          path: results/
